# Generated by Django 2.2.1 on 2019-05-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190507_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
