# Generated by Django 2.2.1 on 2019-05-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190507_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
