# Generated by Django 2.2.1 on 2019-05-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190513_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
