# Generated by Django 2.2.1 on 2019-05-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190513_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='trail_period',
            new_name='trial_period',
        ),
    ]
