# Generated by Django 3.2 on 2021-04-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_date_due'),
        ('core', '0008_auto_20190519_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetasks',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskcategory'),
        ),
        migrations.AddField(
            model_name='templatetasks',
            name='date_due',
            field=models.CharField(choices=[('AI', 'After Info'), ('AS', 'After Signing'), ('PR', 'Preparation'), ('BF', 'Before Work Start'), ('FR', 'First Day of Work'), ('AF', 'After First Day of Work')], default='BF', max_length=2),
        ),
    ]
