# Generated by Django 3.2 on 2021-04-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210407_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatetasks',
            name='category',
        ),
        migrations.RemoveField(
            model_name='templatetasks',
            name='date_due',
        ),
    ]
