# Generated by Django 2.2.1 on 2019-05-30 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20190530_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
