# Generated by Django 3.2 on 2021-04-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20190605_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingtasks',
            name='state',
            field=models.CharField(choices=[('CM', 'Completed'), ('ST', 'Open'), ('PR', 'Processed'), ('NC', 'Not necessary')], default='ST', max_length=2),
        ),
    ]
